# Generated by Django 2.1.11 on 2019-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mandatory_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
            options={
                'verbose_name': 'mandatory_video',
                'verbose_name_plural': '軍事訓練役',
            },
        ),
        migrations.CreateModel(
            name='voluntary_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
            options={
                'verbose_name': 'voluntary_video',
                'verbose_name_plural': '志願役',
            },
        ),
    ]
