# Generated by Django 2.1.11 on 2019-08-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatory_video',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mandatory_video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='voluntary_video',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='voluntary_video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
