# Generated by Django 2.1 on 2019-08-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_playlist', '0002_auto_20190820_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatory_video',
            name='cover_img',
            field=models.FileField(blank=True, null=True, upload_to='image/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='voluntary_video',
            name='cover_img',
            field=models.FileField(blank=True, null=True, upload_to='image/', verbose_name=''),
        ),
    ]
