# Generated by Django 2.1 on 2019-08-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_playlist', '0003_auto_20190821_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatory_video',
            name='cover_img',
            field=models.FileField(blank=True, null=True, upload_to='image/', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='mandatory_video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='voluntary_video',
            name='cover_img',
            field=models.FileField(blank=True, null=True, upload_to='image/', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='voluntary_video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video'),
        ),
    ]
